data_source retail:
  type: bigquery
  account_info_json_path: /usr/local/airflow/include/gcp/gcp_connection.json
  auth_scopes:
  - https://www.googleapis.com/auth/bigquery
  - https://www.googleapis.com/auth/cloud-platform
  - https://www.googleapis.com/auth/drive
  project_id: 'gcplearner-408018'
  dataset: retail
soda_cloud:
  host: cloud.us.soda.io
  api_key_id: acfb4163-9613-4db3-8468-781896cbf6dc
  api_key_secret: ldidYZ9zXjsdcZTnM20WzVxVzQZu5KyycoP_AGNe0n3sapzARQ1_cg